### ISSUE TITLE
Wrong Zoom Extents for layer loaded directly after Himawari 8 in a story

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#148]
(confirmed on dotmaps and landsat - less clear on choropleths)
When Himawari 8 (19 of Top 50) is loaded in story view, the next layer chosen does not zoom to its expected level, but instead pauses zoom at some wider extent. The second waypoint loaded (or the original one clicked again) corrects the issue, but it returns each time Himawari is visited.

Incorrect view after Himawari 8
![image](https://user-images.githubusercontent.com/42879120/95995794-f39e6e00-0dff-11eb-8edf-8ef95b009b67.png)

Correct view
![image](https://user-images.githubusercontent.com/42879120/95995884-0a44c500-0e00-11eb-9c72-cd23a604b124.png)

**Comment by rsargent** [comment]
Fixed with commit 9b6db402f1e7856d90b06c699da284b4e19f5957

**Comment by rsargent** [comment]
Looks like it's confirmed fixed on staging.earthtime.org for clicking waypoints, but not fixed for changing URL hash, which is a different code path.  hal44 test shows this for staging.earthtime.org:
![image](https://user-images.githubusercontent.com/324851/96152262-5bc18280-0eda-11eb-801d-8a022230c7f4.png)

**Comment by pdille** [comment]
How are you all changing the URL hash? If I manually go between the share links (by typing in the address bar) of waypoint 19 and 20, it warps me to each point with the correct view/zoom.

**Comment by pdille** [comment]
Is this still an issue? @hjhawkinsiv @rsargent

**Comment by hjhawkinsiv** [comment]
It does not appear so for Hill 2010 (20/50), however for [Bpop 1990-2010](https://staging.earthtime.org/explore#v=40.42129,-79.93609,10.248,latLng&t=0&ps=0&l=bdrk,bdrk_detailed,allegheny_county_pgh,popchange_black_1990_2010&bt=20100101&et=20100101&startDwell=0&endDwell=0.1&forceLegend=true) (36/50) this still appears to be the case. This layer follows [Himawari 8](https://staging.earthtime.org/explore#v=-24.30021,0.56962,-0.31,latLng&t=0.00&l=blsat,h8) (35/50).

![image](https://user-images.githubusercontent.com/8990930/96621278-4cb54880-12bd-11eb-8667-097f5f0374d0.png)

**Comment by jjkohler** [comment]
No evidence of this still occurring in actual site use. This seems at worst a testing issue. Closing unless concrete evidence re-emerges.
